openapi: "3.0.2"
info:
  title: "osaop backend"
  version: "1.00"
servers:
  - url: http://localhost:8085/api
paths:
  /login:
    post:
      summary: Вход в систему
      operationId: login
      tags:
        - LOGIN
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/loginDto"
      responses:
        200:
          description: Пустой ответ

  /logout:
    post:
      summary: Выход из системы
      operationId: logout
      tags:
        - LOGIN
      responses:
        200:
          description: Пустой ответ
  /admin/roles:
    get:
      summary: Выборка списка ролей
      operationId: getRoles
      tags:
        - ADMIN
      responses:
        200:
          description: Список ролей
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/rolesDto"
  /admin/trackTimeMetrics:
    get:
      summary: Выборка статистики выполнения методов
      operationId: getTrackTimeMetrics
      tags:
        - ADMIN
      responses:
        200:
          description: Статистика выполнения методов
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/trackTimesViewDto"
  /animal/animalTypes:
    get:
      summary: Выборка типов животных
      operationId: getAnimalTypes
      tags:
        - ANIMAL
      responses:
        200:
          description: Список типов животных
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/animalTypesDto"
    post:
      summary: Добавление типа животных
      operationId: addAnimalType
      tags:
        - ANIMAL
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/refRecordInDto"
      responses:
        200:
          description: Тип животного
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/refRecordDto"
  /animal/animalTypes/{id}:
    get:
      summary: Выборка типа животного
      operationId: getAnimalType
      tags:
        - ANIMAL
      parameters:
        - name: id
          description: Идентификатор
          in: path
          required: true
          schema:
            type: integer
            format: int64
      responses:
        200:
          description: Тип животного
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/refRecordDto"
    patch:
      summary: Изменение типа животных
      operationId: modifyAnimalType
      tags:
        - ANIMAL
      parameters:
        - name: id
          description: Идентификатор
          in: path
          required: true
          schema:
            type: integer
            format: int64
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/refRecordInDto"
      responses:
        200:
          description: Тип животного
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/refRecordDto"
  /animal/animals:
    get:
      summary: Выборка животных
      operationId: getAnimals
      tags:
        - ANIMAL
      responses:
        200:
          description: Список животных
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/animalsViewDto"
    post:
      summary: Добавление животного
      operationId: addAnimal
      tags:
        - ANIMAL
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/animalInDto"
      responses:
        200:
          description: Животное
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/animalViewDto"
  /animal/animals/{id}:
    get:
      summary: Выборка животного
      operationId: getAnimal
      tags:
        - ANIMAL
      parameters:
        - name: id
          description: Идентификатор
          in: path
          required: true
          schema:
            type: integer
            format: int64
      responses:
        200:
          description: Тип животного
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/animalViewDto"
    patch:
      summary: Изменение животного
      operationId: modifyAnimal
      tags:
        - ANIMAL
      parameters:
        - name: id
          description: Идентификатор
          in: path
          required: true
          schema:
            type: integer
            format: int64
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/animalInDto"
      responses:
        200:
          description: Животное
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/animalViewDto"
components:
  schemas:
    rolesDto:
      type: array
      description: Список ролей
      items:
        $ref: "#/components/schemas/refRecordDto"
    refRecordDto:
      type: object
      description: Строка справочника
      properties:
        id:
          type: integer
          format: int64
          description: Идентификатор
          example: 1
        name:
          type: string
          description: Наименование
          example: Наименование 1
    refRecordInDto:
      type: object
      description: Строка справочника
      properties:
        name:
          type: string
          description: Наименование
          example: Наименование 1
    roleFullViewDto:
      type: object
      description: Данные по роли
      properties:
        id:
          type: integer
          format: int64
          description: Идентификатор записи
          example: 1
        name:
          type: string
          description: Наименование роли
          example: ADMIN
    loginDto:
      type: object
      description: Данные для входа в систему
      properties:
        username:
          type: string
          description: Имя пользователя
          example: ADMIN
        password:
          type: string
          description: Наименование
          example: ADMIN
    animalTypesDto:
      type: array
      description: Список типов животных
      items:
        $ref: "#/components/schemas/refRecordDto"
    animalsViewDto:
      type: array
      description: Список животных
      items:
        $ref: "#/components/schemas/animalViewDto"
    animalViewDto:
      type: object
      description: Данные о животном
      properties:
        id:
          type: integer
          format: int64
          description: Идентификатор
          example: 1
        name:
          type: string
          description: Наименование
          example: Наименование 1
        legs:
          type: integer
          format: int64
          description: Количество ног
          example: 1
        animalTypeId:
          type: integer
          format: int64
          description: Идентификатор типа
          example: 1
        animalTypeName:
          type: string
          description: Наименование типа
          example: Птица
    animalInDto:
      type: object
      description: Данные о животном
      properties:
        name:
          type: string
          description: Наименование
          example: Наименование 1
        legs:
          type: integer
          format: int64
          description: Количество ног
          example: 2
        animalTypeId:
          type: integer
          format: int64
          description: Идентификатор типа
          example: 1

    trackTimesViewDto:
      type: array
      description: Выборка статистики выполнения для методов
      items:
        $ref: "#/components/schemas/trackTimeViewDto"
    trackTimeViewDto:
      type: object
      description: Статистика выполнения для метода
      properties:
        methodName:
          type: string
          description: Наименование метода
          example: getAnimals
        execCount:
          type: integer
          format: int64
          description: Количество выполнений
          example: 1
        execSum:
          type: integer
          format: int64
          description: Суммароное время выполнений
          example: 1
        execMin:
          type: integer
          format: int64
          description: Минимальное время  выполнения
          example: 1
        execMax:
          type: integer
          format: int64
          description: Максимальное время  выполнения
          example: 1
        execAvg:
          type: integer
          format: int64
          description: Среднее время  выполнения
          example: 1
